package com.earl.gpns.domain.webSocketActions.services

import com.earl.gpns.domain.webSocketActions.NewTripInviteNotification
import com.earl.gpns.domain.webSocketActions.RemoveDeletedSearchingFormFromList

interface SearchingSocketService : NewTripInviteNotification, RemoveDeletedSearchingFormFromList